// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vllepqdeliblcykuqoyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsbGVwcWRlbGlibGN5a3Vxb3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Njg5NDAsImV4cCI6MjA2NTA0NDk0MH0.Oy6YslbfnIlRuzKrmppdrjLqwCEFpr3zfe7EZu7hE_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);